global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway (NestJS)
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Frontend (Next.js)
  - job_name: 'frontend'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Workers (FastAPI)
  - job_name: 'story-architect'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'quest-designer'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'dialogue-writer'
    static_configs:
      - targets: ['host.docker.internal:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'lore-keeper'
    static_configs:
      - targets: ['host.docker.internal:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'simulator'
    static_configs:
      - targets: ['host.docker.internal:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'exporter'
    static_configs:
      - targets: ['host.docker.internal:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # NATS
  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
